spring.application.name=identity-service
# Cấu hình Port chạy cho dịch vụ Java Auth (Tránh trùng với .NET và Angular)
server.port=8081

# Cấu hình kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Ecommerce_IdentityDb;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate (JPA) tự động cập nhật cấu trúc bảng nếu có thay đổi từ code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chuỗi này phải dài tối thiểu 32 ký tự (256-bit) để đảm bảo thuật toán mã hóa chạy an toàn
jwt.signerKey=c3VwZXItc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw==
#cấu hình mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hunggokai@gmail.com
spring.mail.password=qlif gkvz bzzy whtu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cấu hình VNPay Sandbox (Dùng để test miễn phí)
vnp.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.tmnCode=2QXUI4J4
vnp.hashSecret=AEXYZ123456789ABCDEF123456789ABCDEF
vnp.returnUrl=http://localhost:8081/orders/vnpay-return





file.temp-dir=local_temp_uploads